apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
      containers:
      - image: my-telegraf:latest
        imagePullPolicy: Never
        name: telegraf
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
          readOnly: false