apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: my-wordpress:latest
        imagePullPolicy: Never
        name: wordpress
        ports:
        - name: http
          containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: http
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer