apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-phpmyadmin-deployment
  labels:
    app: my-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-phpmyadmin
  template:
    metadata:
      labels:
        app: my-phpmyadmin
    spec:
      containers:
        - name: my-phpmyadmin
          image: my-phpmyadmin:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: my-phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: my-phpmyadmin
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000